apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod
  namespace: app
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: cert-testing
  dnsNames:
  - www.ajin.online
