
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: app
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: achuabhin86@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: kong
# issuer-lets-encrypt-staging.yaml
